from django.urls import path
from .views import *

urlpatterns = [
    path('accounts/login/',logoutNew),
    path('', loginPage),
    path('login',loginAndRedirect),
    path('logout',logoutNew),

    #reports
    path('all',managementDashboard),
    path('reports/<str:cid>', mgtReport),
    path('bigo-reports',bigoReport),
    path('aadya-reports',aadyaReport),
    path('aditya-birla-cellulose-reports',adityaBirlaCelluloseReport),
    path('aditya-birla-toll-free-reports',adityaBirlaTollFreeReport),
    path('aditya-birla-nps-reports',adityaBirlaNPSReport),
    path('aditya-birla-retailer-calling-nps-reports',adityaBirlaRetailerCallingReport),
    path('aditya-birla-website-enquiry-reports',adityaBirlaWebsiteEnquiryReport),
    path('akdy-calls',aKDYcallsReport),
    path('avenue-living-communities',avenueLivingCommunitiesReport),
    path('bhagyalaxmi-industries',bhagyalaxmiIndustriespractoReport),
    path('bng-vs-php',bNGvsPHPreport),
    path('career-transition-specialist',careerTransitionSpecialistReport),
    path('citizen-capital',citizenCapitalReport),
    path('core-small-insurance-agency-inc',coreySmallInsuranceAgencyIncReport),
    path('cross-tower',crossTowerReport),
    path('csc-service-works',cSCserviceWorksReport),
    path('daniel-wellington',danielWellingtonReport),
    path('digital-signage',digitalSignageReport),
    path('digital-swiss-gold',digitalSwissGoldReport),
    path('ee-hh-aaa',eEHHAAAreport),
    path('embassy-premium',embassyPremiumReport),
    path('fame-house',fameHouseReport),
    path('fitness-mortgage',fitnessMortgageReport),
    path('genesis-acquisition',genesisAccquisitionReport),
    path('golden-eye-cctv',goldenEyeCCTVreport),
    path('gubagoo',gUbagooReport),
    path('hindalco',hindalcoReport),
    path('ilm',iLMreport),
    path('imaginarium',imaginariumSolutionsLTDreport),
    path('imprint-plus',imprintPlusReport),
    path('insalvage',iNsalvageReport),
    path('kaapi-machines',kaapiMachinesReport),
    path('lawoffice-m-geller',lawOfficesRobertMgellerReport),
    path('marcelo-perez',marceloPerezStateFarmReport),
    path('marin-rv-storage',marinRVstorageReport),
    path('medicare',mediCareReport),
    path('mob-twenty-two',mobileTwentyTwoReport),
    path('monster-lead',monsterLeadReport),
    path('movement-insurance',movementInsuranceReport),
    path('naffa-innovations',naffaInnovationsReport),
    path('new-dim-pharmacy',newDimensionPharmacyReport),
    path('noom',noomReport),
    path('printer-pix',printerPixReport),
    path('protostar',protostarReport),
    path('rainbow-dia-lts',rainbowDiagnosticsLTSreport),
    path('sana-life-science',sanaLifeScienceReport),
    path('saura-khalki-fashion',saurabhaktiKhalkiFasionReport),
    path('schindler-media',schindlerMediaReport),
    path('somethings-brewing',somethingsBrewingReport),
    path('sterling-strategies-llc',sterlingStrategiesLLCreport),
    path('tanaor-jewelry-lsrael-ltd',tanaorJewelryIsraelLtdReport),
    path('tca-counseling-group',tCAcounselingGroupReport),
    path('tech-report',techReport),
    path('us-jaclean-inc',uSJacleanINCreport),
    path('ups-nps',uPSNPSreport),
    path('window-treatment-unlimited',windowTreatmentUnlimitedReport),
    path('winopoly', winopolyReport),
    path('allcare-phycical',allCarePhysicalTherapy),
    path('blazing-hog',blazingHogAndWahooInternet),
    path('bright-way',brightWay),
    path('calista',Calista),
    path('global-arc',globalARC),
    path('jiffy-ship-cargo',jiffyShipCargo),
    path('pick-pack-delivery',pickPackDelivery),
    path('sapphire-medicals',sapphireMedicals),
    path('management',managementDashboard),
    path('settings', change_password),
    path('practo', PractoReport)
]